# docker-compose.yml
version: '3.8'

networks:
  estateagent_net:
    driver: bridge

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - estateagent_net